require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - '**/*_pb.rb'
    - 'vendor/**/*'

  TargetRubyVersion: 2.5

  NewCops: enable

Metrics:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false
